export const ADD_TOKEN = "ADD_TOKEN";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const DELETE_TOKEN = "DELETE_TOKEN";
export const DCR_LIST = "DCR_LIST";
export const RCPA_LIST = "RCPA_LIST";
export const TOGGLE_DCR_HEADER = "TOGGLE_DCR_HEADER";
export const TOGGLE_RCPA_HEADER = "TOGGLE_RCPA_HEADER";
export const IS_FULL = "IS_FULL";
export const IS_RCPA_FULL = "IS_RCPA_FULL"
export const DCR_PRODUCT = "DCR_PRODUCT";
export const DCR_POB = "DCR_POB";
export const COMPLETED_TASK = "COMPLETED_TASK";
export const DOCTOR_PROFILE = "DOCTOR_PROFILE";
export const DCR_JOINT = "DCR_JOINT";
//export const MASTER_LIST="MASTER_LIST"
//export const MASTERheader="MASTERheader"
export const SET_MASTER_DATA = "SET_MASTER_DATA";
export const MASTEREDIT = "MASTEREDIT";
export const GET_OACTIVITY = "GET_OACTIVITY";
export const PLANNED_TASK = "PLANNED_TASK";
export const UN_PLANNED_TASK = "UN_PLANNED_TASK";
export const PRE_PLANNED_TASK = "PRE_PLANNED_TASK";
export const DCR_DROPDOWN = "DCR_DROPDOWN";
export const TODAY_EVENTS = "TODAY_EVENTS";
export const DCR_PRAMOTIONS = "DCR_PRAMOTIONS";
export const DOCTOR_DETAIL = "DOCTOR_DETAIL";
export const DOCTOR_AREA = "DOCTOR_AREA";
export const DCR_SEARCH = "DCR_SEARCH";
export const DCR_STAYED = "DCR_STAYED";
export const DCR_RCPA = "DCR_RCPA";
export const NOTIFICATIONS = "NOTE";
export const SET_PLANNED_DATE = "SET_PLANNED_DATE";
export const RCPAdetails='RCPAdetails'


//export const MASTER_FILTER="MASTER_FILTER"
export const REQUEST="REQUEST";
export const APPROVAl="APPROVAl";
export const REQUEST_TYPE="REQUEST_TYPE";
export const REQUEST_STATUS = "REQUEST_STATUS"

//exporting mr dahboard constants 
export const MR_PROGRESS="MR_PROGRESS"
export const MR_CALLAVERAGE_TABLE="MR_CALLAVERAGE_TABLE"
export const MR_UNCOVERDOCTOR_DATA="MR_UNCOVERDOCTOR_DATA"
export const MR_NONPERFORMING_DATA="MR_NONPERFORMING_DATA"
export const MR_MONTHLY_CLAIM="MR_MONTHLY_CLAIM"
export const MR_CALL_AVERAGE_GRAPH="MR_CALL_AVERAGE_GRAPH"
export const SAMPLES = "SAMPLES"
export const MR_SECONDARY_SALES_GRAPH="MR_SECONDARY_SALES_GRAPH"
export const MR_LEADERBOARD_DATA="MR_LEADERBOARD_DATA"
export const MR_SECONDRY_STATE= "MR_SECONDRY_STATE"
export const MR_APICALL_STATE ="MR_APICALL_STATE"
export const DROP_Year ="DROP_Year"
export const DROP_SEC_YEAR="DROP_SEC_YEAR"

//exporting manager dahboard constants
export const MANAGER_MONTH_LIST="MANAGER_MONTH_LIST"
export const MANAGER_DESIGNATION_LIST="MANAGER_DESIGNATION_LIST"
export const GET_OTP = "GET_OTP"
export const MANAGER_PROGRESS="MANAGER_PROGRESS"
export const MANAGER_SECONDARY_SALES_GRAPH="MANAGER_SECONDARY_SALES_GRAPH"
export const MANAGER_UNCOVER_DOCTOR="MANAGER_UNCOVER_DOCTOR"
export const MANAGER_MY_WORK_DETAILS="MANAGER_MY_WORK_DETAILS"
export const MANAGER_MY_TEAM_WORK_DETAILS="MANAGER_MY_TEAM_WORK_DETAILS"
export const MANAGER_DOWN_CALL_AVERAGE="MANAGER_DOWN_CALL_AVERAGE"
export const SET_COMPLETED_PLANNEDTASK="SET_COMPLETED_PLANNEDTASK"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const MANAGER_LEADER_BOARD="MANAGER_LEADER_BOARD"
export const MANAGER_API_STATE="MANAGER_API_STATE"
export const GET_CALLAVG_DOWNLINE ="GET_CALLAVG_DOWNLINE"
export const GET_WORK_DOWNLINE="GET_WORK_DOWNLINE"
export const GET_SEC_STATE="GET_SEC_STATE"
export const GET_TEAMSALES_REPORT="GET_TEAMSALES_REPORT"
export const GET_LEADER_STATE="GET_LEADER_STATE"
export const GET_SALES_YEAR="GET_SALES_YEAR"
export const GET_TEAM_YEAR="GET_TEAM_YEAR"


//exporting admin dahboard constants
export const LEAVE_STATUS = "LEAVE_STATUS"
export const CLAIM_STATUS = "CLAIM_STATUS"
export const MTP_STATUS = "MTP_STATUS"
export const DWR_STATUS = "DWR_STATUS"
export const ADMIN_REQUEST_STATUS= "ADMIN_REQUEST_STATUS"
export const ADMIN_STATUS="ADMIN_STATUS"
export const ADMIN_REQUEST_LIST="ADMIN_REQUEST_LIST"
export const ADMIN_UNLOCK_LIST="ADMIN_UNLOCK_LIST"
export const ADMIN_DOC_LIST="ADMIN_DOC_LIST"
export const ADMIN_MTP_MONTH ="ADMIN_MTP_MONTH"
export const ADMIN_MTP_LIST = "ADMIN_MTP_LIST"
export const ADMIN_SWRSUB_LIST = "ADMIN_SWRSUB_LIST"
export const ADMIN_SWRSUB_FILTER = "ADMIN_SWRSUB_FILTER"
export const ADMIN_UNLOCK_FILTER = "ADMIN_UNLOCK_FILTER"
export const ADMIN_CONFIRM_LIST= "ADMIN_CONFIRM_LIST"

export const REQUEST_DOWNLINE="REQUEST_DOWNLINE"


// export Leave constant

export const HOLIDAY_LEAVE = "HOLIDAY_LEAVE"
export const LEAVE_REQUEST = "LEAVE_REQUEST"
export const APPLY_LEAVE_TYPE = "APPLY_LEAVE_TYPE"
export const LEAVE_DETAIL = "LEAVE_DETAIL"
export const LEAVE_STATUS1 = "LEAVE_STATUS1"
export const REQUEST_LEAVE_UPDATE = "REQUEST_LEAVE_UPDATE"


//STP
export const STP_PATCH = "STP_PATCH"
export const STP_TARGET = "STP_TARGET"
export const STP_DAYS = "STP_DAYS"
export const STP_AREA_INFO= "STP_AREA_INFO"
export const LOGOUT = "LOGOUT"

//exporting Expense constantss
export const ENTRY_TYPE = "ENTRY_TYPE"



//MTP 
export const MTP_TARGET = "MTP_TARGET"
export const MTP_PLANNED ="MTP_PLANNED"
export const MTP_DAYS = "MTP_DAYS"
export const MTP_PATCH = "MTP_PATCH"
export const MTP_DOWNLINE_PATCH="MTP_DOWNLINE_PATCH"

//RPS
export const RPS_LIST = "RPS_LIST"

//material
export const MATERIAL_LIST = "MATERIAL_LIST"
export const MATERIAL_CONFIRM_LIST ="MATERIAL_CONFIRM_LIST"