export default [{
    "id": 1,
    "value": "1",
    "label": "January"
  }, {
    "id": 2,
    "value": "2",
    "label": "February"
  }, {
    "id": 3,
    "value": "3",
    "label": "March"
  }, {
    "id": 4,
    "value": "4",
    "label": "April"
  }, {
    "id": 5,
    "value": "5",
    "label": "May"
  }, {
    "id": 6,
    "value": "6",
    "label": "June"
  }, {
    "id": 7,
    "value": "7",
    "label": "July"
  },  {
    "id": 8,
    "value": "8",
    "label": "August"
  }, {
    "id": 9,
    "value": "9",
    "label": "September"
  }, {
    "id": 10,
    "value": "10",
    "label": "October"
  }, {
    "id": 11,
    "value": "11",
    "label": "November "
  }, {
    "id": 12,
    "value": "12",
    "label": "December"
  }]